development:
  dialect: "mysql"
  database: olympusdb
  host: 127.0.0.1
  port: 3307
  user: vgp
  password: vgp

test_postgres:
  dialect: "postgres"
  database: athens_development
  user: postgres
  password: ''
  host: 127.0.0.1
  pool: 5

test:
  dialect: "mysql"
  database: olympusdb
  host: 127.0.0.1
  port: 3306
  user: vgp
  password: vgp
  
production:
  dialect: "mysql"
  database: olympusdb
  host: {{ env "DB_HOST" }}
  port: {{ env "DB_PORT" }}
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASS" }}
