(ns athens.athens-datoms)

;; athens namespaced pages that are updated when app is updated
(def datoms
  [{:db/id 1,
    :block/uid "0",
    :block/children [{:db/id 339,
                      :block/uid "a6f7b01cf",
                      :block/string "Welcome to Athens, Open-Source Networked Thought!",
                      :block/open true,
                      :block/order 0}
                     {:db/id 903,
                      :block/uid "9f8187d34",
                      :block/string "You can connect pages together with bi-directional links. You are currently on [[athens/Welcome]]. If you go to [[athens/Changelog]], you will see this block in \"Linked References\".",
                      :block/open true,
                      :block/order 1}
                     {:db/id 689,
                      :block/uid "3938f6d7b",
                      :block/string "Athens is persisted to your filesystem at `documents/athens`. Soon you will be able to choose any location for your db (including Dropbox folders).",
                      :block/open true,
                      :block/order 2}
                     {:db/id 906,
                      :block/uid "6de8b7d13",
                      :block/string "[[athens/Welcome]] and [[athens/Changelog]] are reserved pages. When a new version of Athens is deployed, your app will update automatically. These pages will be updated as well. Any changes you make to these pages will be overwritten, so don't write anything you need in these pages!",
                      :block/open true,
                      :block/order 3}
                     {:db/id 909, :block/uid "365c52fff", :block/string "", :block/open true, :block/order 4}
                     {:db/id 908,
                      :block/uid "5c872acd9",
                      :block/string "You can click on a bullet [insert ascii bullet] to zoom-in on it.",
                      :block/open true,
                      :block/order 5,
                      :block/children [{:db/id 932,
                                        :block/uid "f0bad2f38",
                                        :block/string "If a block has a `>` or `v` to the left of its bullet, that means it has children. You can click the `v` and `>` to open and close the bullet.",
                                        :block/open true,
                                        :block/order 0}]}
                     {:db/id 372,
                      :block/uid "a0b16ab19",
                      :block/string "Outliner Features",
                      :block/open false,
                      :block/order 6,
                      :block/children [{:db/id 373,
                                        :block/uid "d6c47a7f4",
                                        :block/string "Indent and unindent bullets with tab and shift-tab.",
                                        :block/open true,
                                        :block/order 0}
                                       {:db/id 375,
                                        :block/uid "2f53541d7",
                                        :block/string "Drag and drop bullets to re-order blocks.",
                                        :block/open true,
                                        :block/order 1}
                                       {:db/id 376,
                                        :block/uid "41a752cb5",
                                        :block/string "Select multiple bullets with click and drag or shift-up or shift-down.",
                                        :block/open true,
                                        :block/order 2}]}
                     {:db/id 340,
                      :block/uid "f5dd95e6e",
                      :block/string "Markup Features",
                      :block/open false,
                      :block/order 7,
                      :block/children [{:db/id 341,
                                        :block/uid "c9e48f596",
                                        :block/string "Bold text with **double asterisks**",
                                        :block/open true,
                                        :block/order 0}
                                       {:db/id 342,
                                        :block/uid "9f727fd2b",
                                        :block/string "Mono-spaced text with `backticks`",
                                        :block/open true,
                                        :block/order 1}
                                       {:db/id 343,
                                        :block/uid "5d19451db",
                                        :block/string "Links with `[[]]`, `#`, or `#[[]]`: [[athens/Welcome]] #athens/Welcome #[[athens/Welcome]]",
                                        :block/open true,
                                        :block/order 2}
                                       {:db/id 347,
                                        :block/uid "ddcf4ba1f",
                                        :block/string "Block references with `(())`: ((82247e489))",
                                        :block/open true,
                                        :block/order 3,
                                        :block/children [{:db/id 362,
                                                          :block/uid "82247e489",
                                                          :block/string "I am being referenced",
                                                          :block/open true,
                                                          :block/order 0,
                                                          :block/_refs [#:db{:id 347}]}]}
                                       {:db/id 348,
                                        :block/uid "5ac7f905f",
                                        :block/string "{{[[TODO]]}} `ctrl-enter` to cycle between TODO and DONE",
                                        :block/open true,
                                        :block/order 4}
                                       {:db/id 350,
                                        :block/uid "f22247778",
                                        :block/string "embeds with `{{[[youtube: ]]}}` and `{{``iframe: }}`",
                                        :block/open false,
                                        :block/order 5,
                                        :block/children [{:db/id 352,
                                                          :block/uid "2da5522a1",
                                                          :block/string "{{[[youtube]]: https://www.youtube.com/watch?v=dQw4w9WgXcQ}}",
                                                          :block/open true,
                                                          :block/order 0}
                                                         {:db/id 353,
                                                          :block/uid "50cfadc73",
                                                          :block/string "{{iframe: https://www.openstreetmap.org/export/embed.html?bbox=-0.004017949104309083%2C51.47612752641776%2C0.00030577182769775396%2C51.478569861898606&layer=mapnik}}",
                                                          :block/open true,
                                                          :block/order 1}]}
                                       {:db/id 351,
                                        :block/uid "2af204111",
                                        :block/string "images with `![]()` ![athens-splash](https://raw.githubusercontent.com/athensresearch/athens/master/doc/athens-puk-patrick-unsplash.jpg)",
                                        :block/open true,
                                        :block/order 6}]}
                     {:db/id 354,
                      :block/uid "eda8f737a",
                      :block/string "All Keybindings",
                      :block/open false,
                      :block/order 8,
                      :block/children [{:db/id 913,
                                        :block/uid "6684acffe",
                                        :block/string "local shortcuts (within a block)",
                                        :block/open true,
                                        :block/order 0,
                                        :block/children [{:db/id 355,
                                                          :block/uid "19c858229",
                                                          :block/string "`ctrl-b`: **bold**",
                                                          :block/open true,
                                                          :block/order 0}
                                                         {:db/id 912,
                                                          :block/uid "dfc7e935e",
                                                          :block/string "`/`: slash commands",
                                                          :block/open true,
                                                          :block/order 1}
                                                         {:db/id 915,
                                                          :block/uid "30e54f370",
                                                          :block/string "`tab`: indent",
                                                          :block/open true,
                                                          :block/order 2}
                                                         {:db/id 923,
                                                          :block/uid "1ecab0585",
                                                          :block/string "`shift-tab`: unindent block ",
                                                          :block/open true,
                                                          :block/order 3}
                                                         {:db/id 918,
                                                          :block/uid "39e46d281",
                                                          :block/string "`shift-up` or `shift-down`: select multiple blocks",
                                                          :block/open true,
                                                          :block/order 4}
                                                         {:db/id 927,
                                                          :block/uid "8f5ff2896",
                                                          :block/string "`ctrl-a`: select all blocks on page",
                                                          :block/open true,
                                                          :block/order 5}
                                                         {:db/id 920,
                                                          :block/uid "2c3a20456",
                                                          :block/string "`ctrl-z`: undo",
                                                          :block/open true,
                                                          :block/order 6}
                                                         {:db/id 922,
                                                          :block/uid "e6dfe6693",
                                                          :block/string "`ctrl-shift-z`: redo",
                                                          :block/open true,
                                                          :block/order 7}]}
                                       {:db/id 914,
                                        :block/uid "2960a50f4",
                                        :block/string "global shortcuts (can use anywhere)",
                                        :block/open true,
                                        :block/order 1,
                                        :block/children [{:db/id 364,
                                                          :block/uid "33f88d8d6",
                                                          :block/string "`ctrl-\\`: open left sidebar",
                                                          :block/open true,
                                                          :block/order 0}
                                                         {:db/id 365,
                                                          :block/uid "72d86bbb0",
                                                          :block/string "`ctrl-shift-\\`: open right sidebar",
                                                          :block/open true,
                                                          :block/order 1}
                                                         {:db/id 366,
                                                          :block/uid "c993bf326",
                                                          :block/string "`ctrl-k`: open search bar",
                                                          :block/open true,
                                                          :block/order 2}]}]}
                     {:db/id 368,
                      :block/uid "020a90740",
                      :block/string "Left Sidebar",
                      :block/open true,
                      :block/order 9,
                      :block/children [{:db/id 371,
                                        :block/uid "a82850462",
                                        :block/string "Mark a page as a shortcut with the caret next to the page title.",
                                        :block/open true,
                                        :block/order 0}]}
                     {:db/id 369,
                      :block/uid "539723d85",
                      :block/string "Right Sidebar",
                      :block/open true,
                      :block/order 10,
                      :block/children [{:db/id 370,
                                        :block/uid "4e12e40ed",
                                        :block/string "Open a block or page in the right sidebar by shift clicking on the title or bullet.",
                                        :block/open true,
                                        :block/order 0}]}]}
   {:node/title     "athens/Changelog",
    :block/children [{:block/string   "[[September 29, 2020]]",
                      :block/children [{:block/string "The beginning of the in-Athens Changelog.",
                                        :block/uid    "8eb0523bd",
                                        :block/open   true,
                                        :db/id        382,
                                        :block/order  0}],
                      :block/uid      "52604194d",
                      :block/open     true,
                      :db/id          380,
                      :block/order    0}],
    :block/uid      "1",
    :db/id          378
    :page/sidebar   1000}])
