package gcp

import (
	"context"
	"testing"
	"time"

	"cloud.google.com/go/storage"
	"github.com/gobuffalo/envy"
	"github.com/gomods/athens/pkg/config"
	"github.com/stretchr/testify/suite"
	"google.golang.org/api/option"
	"google.golang.org/appengine/aetest"
)

var (
	mod  = []byte{1, 2, 3}
	zip  = []byte{4, 5, 6}
	info = []byte{7, 8, 9}
)

type GcpTests struct {
	suite.Suite
	context context.Context
	options option.ClientOption
	bucket  string
	module  string
	version string
}

func (g *GcpTests) SetupSuite() {
	// this is the test project praxis-cab-207400.appspot.com
	// administered by robbie <robjloranger@protonmail.com>
	// the variable ATHENS_STORAGE_GCP_SA should point to the test key json file
	// and must be set for this test which otherwise will be skipped
	creds, err := envy.MustGet("ATHENS_STORAGE_GCP_SA")
	if err != nil {
		g.T().Skip()
	}
	g.options = option.WithCredentialsFile(creds)
	ctx, done, err := aetest.NewContext()
	defer done()
	if err != nil {
		g.T().Fatalf("could not create new aetest context: %s", err)
	}
	g.context = ctx
	g.bucket = "staging.praxis-cab-207400.appspot.com"
	// time stamped test module names will prevent concurrent test interference
	g.module = "gcp-test" + time.Now().String()
	g.version = "v1.2.3"
	envy.Set("ATHENS_STORAGE_GCP_BUCKET", "staging.praxis-cab-207400.appspot.com")
}

func (g *GcpTests) TearDownSuite() {
	client, err := storage.NewClient(g.context, g.options)
	if err != nil {
		g.T().Fatalf("could not create new storage client: %s", err)
	}

	bkt := client.Bucket(g.bucket)

	// remove all files and directories from this test
	err = cleanBucket(g.context, bkt, g.module, g.version)
	if err != nil {
		g.T().Fatalf("could not delete one or more files generated by tests: %s", err)
	}
}

// cleanBucket iterates over the bucket contents and deletes everything
// matching the module name. folders do not exist so deleting the
// full object 'path' is sufficient
func cleanBucket(ctx context.Context, bkt *storage.BucketHandle, mod, ver string) error {
	if err := bkt.Object(config.PackageVersionedName(mod, ver, "mod")).Delete(ctx); err != nil {
		return err
	}
	if err := bkt.Object(config.PackageVersionedName(mod, ver, "info")).Delete(ctx); err != nil {
		return err
	}
	if err := bkt.Object(config.PackageVersionedName(mod, ver, "zip")).Delete(ctx); err != nil {
		return err
	}
	return nil
}

func TestGcpStorage(t *testing.T) {
	suite.Run(t, new(GcpTests))
}
