#!/usr/bin/env bash

set -eo pipefail

# This script depends on clj-kondo. Installation instructions for clj-kondo are linked to in CONTRIBUTING.md.

# TODO remove this when all warnings have been fixed
clj-kondo --lint src || echo "
[FIXME] fix above warnings and remove this warning"