#!/usr/bin/env bash

set -eo pipefail

# Find installation instructions here https://github.com/borkdude/clj-kondo/blob/554d7d93e2eb78ff21cfbbee4a084c4b6e089411/doc/install.md

# TODO remove this when all warnings have been fixed
clj-kondo --lint src || echo "
[FIXME] fix above warnings and remove this warning"