#!/usr/bin/env bash

set -eo pipefail

# This script depends on cljstyle. Installation instructions for cljstyle are linked to in CONTRIBUTING.md.

# REVIEW consider rewriting to babashka to make platform independent?

curl -L -O https://github.com/greglook/cljstyle/releases/download/0.12.1/cljstyle_0.12.1_linux.tar.gz
tar -zxvf cljstyle_0.12.1_linux.tar.gz

./cljstyle check